version: 1-alpha.1

releases:
  csssr-blog-storybook:
    name: csssr-blog-storybook
    autodeploy-on: default
    chart: csssr/static-site@~1.1.0
    slack:
      - CKF42GD36 # #csssr_builds
    static-params:
      projectID: csssr-blog-storybook
      tlsSecret: csssr-blog-storybook-tls
    builds:
      - workflow: build-storybook.yaml
        values:
          buildID: build-{{ .Build.RunID }}
  static-site:
    name: csssr-blog
    autodeploy-on: default
    chart: csssr/static-site@~1.1.0
    slack:
      - CKF42GD36 # #csssr_builds
    static-params:
      projectID: csssr-new-blog
      tlsSecret: csssr-new-blog-tls
      notFoundPagePath: 404/index.html
      ingress:
        annotations:
          nginx.ingress.kubernetes.io/server-snippet: |
            rewrite ^/$ /en redirect;
    builds:
      - workflow: deploy_testing.yml
        values:
          buildID: build-{{ .Build.RunID }}
