version: 1-alpha.1

releases:
  csssr-blog-storybook:
    name: csssr-blog-storybook
    cluster: gke-csssr-testing
    autodeploy-on: default
    chart: oci://quay.csssr.cloud/charts/static-site@~1.1.0
    slack:
      - CKF42GD36 # #csssr_builds
    static-params:
      projectID: csssr-blog-storybook
      tlsSecret: csssr-blog-storybook-tls
    builds:
      - workflow: build-storybook.yaml
        values:
          buildID: build-{{ .Build.RunID }}
  csssr-blog-testing:
    name: csssr-blog-production
    cluster: gke-csssr-testing
    autodeploy-on: default
    chart: oci://quay.csssr.cloud/charts/static-site@~1.1.0
    slack:
      - CKF42GD36 # #csssr_builds
    static-params:
      projectID: csssr-new-blog
      tlsSecret: csssr-blog-testing-tls
      notFoundPagePath: 404/index.html
      ingress:
        annotations:
          nginx.ingress.kubernetes.io/server-snippet: |
            rewrite ^/$ https://$http_host/en redirect;
    builds:
      - workflow: build-testing.yaml
        values:
          buildID: build-{{ .Build.RunID }}
  csssr-blog-production:
    name: csssr-blog-production
    cluster: gke-csssr-production
    base: csssr-blog-testing
    autodeploy-on:
      push:
        - master
    static-params:
      projectID: csssr-new-blog
      host: blog.csssr.com
      environment: production
      notFoundPagePath: 404/index.html
      cache: etag-only
      reduceHttpRedirects: enabled
      ingress:
        annotations:
          nginx.ingress.kubernetes.io/server-snippet: |
            rewrite ^/$ https://$http_host/en redirect;
    builds:
      - workflow: build-production.yaml
        values:
          buildID: build-{{ .Build.RunID }}
