module.exports = {
  logo: {
    csssr: '#__next > footer > div.top-content > div > a',
  },
  link: {
    changeLocal: '#__next > footer > div.bottom-content > ul > li:nth-child(1) > a',
    estonia: 'div.address-item.address_estonia > p.title.css-hs6x3x-OriginHeading.e19nz7by0',
    email: '[data-testid="Footer.link.email"]',
    telSingapore: 'footer > div.css-ojpjf3.e1mdmiv0 > div.css-ei2vbe.e19nbpye0 > div.address-item.address_singapore > a',
    telRussia: 'footer > div.css-ojpjf3.e1mdmiv0 > div.css-ei2vbe.e19nbpye0 > div.address-item.address_russia > a',
    telRussiaTwo: 'footer > div.css-ojpjf3.e1mdmiv0 > div.css-ei2vbe.e19nbpye0 > div.address-item.address_russia_2 > a',
    outsourcing: '#__next > footer > div.top-content > nav > div:nth-child(1) > ul > li:nth-child(1) > a',
    backendAndDevops: '#__next > footer > div.top-content > nav > div:nth-child(1) > ul > li:nth-child(2) > a',
    mvp: '#__next > footer > div.top-content > nav > div:nth-child(1) > ul > li:nth-child(3) > a',
    fintech: '#__next > footer > div.top-content > nav > div:nth-child(2) > ul > li:nth-child(1) > a',
    informationTechnology: '#__next > footer > div.top-content > nav > div:nth-child(2) > ul > li:nth-child(2) > a',
    ecommerce: '#__next > footer > div.top-content > nav > div:nth-child(2) > ul > li:nth-child(3) > a',
    mediAndMarketing: '#__next > footer > div.top-content > nav > div:nth-child(2) > ul > li:nth-child(4) > a',
    techStack: '#__next > footer > div.top-content > nav > div:nth-child(3) > ul > li:nth-child(1) > a',
    wayOfWork: '#__next > footer > div.top-content > nav > div:nth-child(3) > ul > li:nth-child(2) > a',
    coreValues: '#__next > footer > div.top-content > nav > div:nth-child(3) > ul > li:nth-child(3) > a',
    ourProjects: '#__next > footer > div.top-content > nav > div:nth-child(3) > ul > li:nth-child(4) > a',
    projects: '#__next > footer > div.top-content > nav > div:nth-child(3) > ul > li:nth-child(4) > a',
    LMS: '#__next > footer > div.top-content > nav > div:nth-child(4) > ul > li:nth-child(1) > a',
    trackingSoftware: '#__next > footer > div.top-content > nav > div:nth-child(4) > ul > li:nth-child(2) > a',
    jobs: '#__next > footer > div.top-content > nav > div:nth-child(4) > ul > li:nth-child(1) > a',
    blog: '#__next > footer > div.top-content > nav > div:nth-child(4) > ul > li:nth-child(2) > a',
    contacts: '#__next > footer > div.top-content > nav > div:nth-child(4) > ul > li:nth-child(3) > a',
    jobsEn: '#__next > footer > div.top-content > nav > div:nth-child(5) > ul > li:nth-child(1) > a',
    blogEn: '#__next > footer > div.top-content > nav > div:nth-child(5) > ul > li:nth-child(2) > a',
    contactsEN: '#__next > footer > div.top-content > nav > div:nth-child(5) > ul > li:nth-child(3) > a',
  },
  block: {
    footer: '#__next > footer',
    map: 'footer > div.css-ojpjf3.e1mdmiv0 > div.map-wrapper > div',
  },
  text: {
    singaporeAddress: '#__next > footer > div.css-ojpjf3.e1mdmiv0 > div.css-ei2vbe.e19nbpye0 > div.address-item.address_singapore > p.address.css-1ahemgd-Text.epkww9c0',
    russianAddress: '#__next > footer > div.css-ojpjf3.e1mdmiv0 > div.css-ei2vbe.e19nbpye0 > div.address-item.address_russia > p.address.css-1ahemgd-Text.epkww9c0',
    russianAddressTwo: '#__next > footer > div.css-ojpjf3.e1mdmiv0 > div.css-ei2vbe.e19nbpye0 > div.address-item.address_russia_2 > p.address.css-1ahemgd-Text.epkww9c0',
    estoniaAddress: '#__next > footer > div.css-ojpjf3.e1mdmiv0 > div.css-ei2vbe.e19nbpye0 > div.address-item.address_estonia > p.address.css-1ahemgd-Text.epkww9c0',
    SingaporeTime: '#__next > footer > div.css-ojpjf3.e1mdmiv0 > div.css-ei2vbe.e19nbpye0 > div.address-item.address_singapore > p.time.css-1ahemgd-Text.epkww9c0',
    RussiaTime: '#__next > footer > div.css-ojpjf3.e1mdmiv0 > div.css-ei2vbe.e19nbpye0 > div.address-item.address_russia > p.time.css-1ahemgd-Text.epkww9c0',
    RussiaTimeTo: '#__next > footer > div.css-ojpjf3.e1mdmiv0 > div.css-ei2vbe.e19nbpye0 > div.address-item.address_russia_2 > p.time.css-1ahemgd-Text.epkww9c0',
    EstoniaTime: '#__next > footer > div.css-ojpjf3.e1mdmiv0 > div.css-ei2vbe.e19nbpye0 > div.address-item.address_estonia > p.time.css-1ahemgd-Text.epkww9c0',
  },
  icon: {
    facebook: '#__next > footer > div.top-content > div > ul > li:nth-child(1) > a',
    linkdIn: '#__next > footer > div.top-content > div > ul > li:nth-child(2) > a',
    instagram: '#__next > footer > div.top-content > div > ul > li:nth-child(3) > a',
    youTube: '#__next > footer > div.top-content > div > ul > li:nth-child(4) > a',
    soundcloud: '#__next > footer > div.top-content > div > ul > li:nth-child(5) > a',
    telegram: '#__next > footer > div.top-content > div > ul > li:nth-child(6) > a',
    twitter: '#__next > footer > div.top-content > div > ul > li:nth-child(7) > a',
    vk: '#__next > footer > div.top-content > div > ul > li:nth-child(8) > a',
  }
}
