module.exports = {
  logo: {
    csssr: '[data-testid="Footer:link:logo"]',
  },
  link: {
    changeLocal: '#__next > footer > div.bottom-content > ul > li:nth-child(1) > a',
    estonia: '#__next > footer > div.css-1ltjtej.e1mdmiv0 > div.css-ei2vbe.e19nbpye0 > div.address-item.address_estonia > p.title.css-zw2p2c.e19nz7by0',
    email: '[data-testid="Footer:link:email"]',
    telSingapore: '#__next > footer > div.css-1ltjtej.e1mdmiv0 > div.css-ei2vbe.e19nbpye0 > div.address-item.address_singapore > a',
    telRussia: '#__next > footer > div.css-1ltjtej.e1mdmiv0 > div.css-ei2vbe.e19nbpye0 > div.address-item.address_russia > a',
    telRussiaTwo: '#__next > footer > div.css-1ltjtej.e1mdmiv0 > div.css-ei2vbe.e19nbpye0 > div.address-item.address_russia_2 > a',
    outsourcing: '[data-testid="Footer:link:web-development"]',

    backendAndDevops: '[data-testid="Footer:link:backend"]',
    mvp: '[data-testid="Footer:link:mvp"]',
    fintech: '[data-testid="Footer:link:fintech"]',
    informationTechnology: '[data-testid="Footer:link:information"]',
    ecommerce: '[data-testid="Footer:link:eCommerce"]',
    mediAndMarketing: '[data-testid="Footer:link:mediaAndMarketing"]',
    techStack: '[data-testid="Footer:link:technologies"]',
    wayOfWork: '[data-testid="Footer:link:wayOfWork"]',
    coreValues: '[data-testid="Footer:link:coreValues"]',
    ourProjects: '[data-testid="Footer:link:projects"]',
    projects: '[data-testid="Footer:link:projects"]',
    LMS: '[data-testid="Footer:link:lms"]',
    trackingSoftware: '[data-testid="Footer:link:tracker"]',
    jobs: '[data-testid="Footer:link:careers"]',
    blog: '[data-testid="Footer:link:blog"]',
    contacts: '[data-testid="Footer:link:contactUs"]',
    outsourcingEn: '[data-testid="Footer:link:outsourcing"]',
    jobsEn: '[data-testid="Footer:link:careers"]',
    blogEn: '[data-testid="Footer:link:blog"]',
    contactsEN: '[data-testid="Footer:link:contactUs"]',
    outsourcing: '#__next > footer > div.top-content > nav > div:nth-child(1) > ul > li:nth-child(1) > a',
    privacyPolicy: '[data-testid="Footer:link:privacyPolicy"]',
  },
  block: {
    footer: '#__next > footer',
    doubleBottom: '[data-testid="Footer:block:DoubleBottom"]',
    map: '#__next > footer > div.css-1ltjtej.e1mdmiv0 > div.map-wrapper > div > img',
  },
  text: {
    singaporeAddress: '#__next > footer > div.css-1ltjtej.e1mdmiv0 > div.css-ei2vbe.e19nbpye0 > div.address-item.address_singapore > p.address.css-awgmvn.epkww9c0',
    russianAddress: '#__next > footer > div.css-1ltjtej.e1mdmiv0 > div.css-ei2vbe.e19nbpye0 > div.address-item.address_russia > p.address.css-awgmvn.epkww9c0',
    russianAddressTwo: '#__next > footer > div.css-1ltjtej.e1mdmiv0 > div.css-ei2vbe.e19nbpye0 > div.address-item.address_russia_2 > p.address.css-awgmvn.epkww9c0',
    estoniaAddress: '#__next > footer > div.css-1ltjtej.e1mdmiv0 > div.css-ei2vbe.e19nbpye0 > div.address-item.address_estonia >  p.address.css-awgmvn.epkww9c0',
    SingaporeTime: '#__next > footer > div.css-ojpjf3.e1mdmiv0 > div.css-ei2vbe.e19nbpye0 > div.address-item.address_singapore > p.time.css-1ahemgd-Text.epkww9c0',
    RussiaTime: '#__next > footer > div.css-ojpjf3.e1mdmiv0 > div.css-ei2vbe.e19nbpye0 > div.address-item.address_russia > p.time.css-1ahemgd-Text.epkww9c0',
    RussiaTimeTo: '#__next > footer > div.css-ojpjf3.e1mdmiv0 > div.css-ei2vbe.e19nbpye0 > div.address-item.address_russia_2 > p.time.css-1ahemgd-Text.epkww9c0',
    EstoniaTime: '#__next > footer > div.css-ojpjf3.e1mdmiv0 > div.css-ei2vbe.e19nbpye0 > div.address-item.address_estonia > p.time.css-1ahemgd-Text.epkww9c0',
  },
  icon: {
    facebook: '[data-testid="Footer:link:facebook"]',
    linkdIn: '[data-testid="Footer:link:linkedin"]',
    instagram: '[data-testid="Footer:link:instagram"]',
    youTube: '[data-testid="Footer:link:youtube"]',
    soundcloud: '[data-testid="Footer:link:soundcloud"]',
    telegram: '[data-testid="Footer:link:telegram"]',
    twitter: '[data-testid="Footer:link:twitter"]',
    vk: '[data-testid="Footer:link:vk"]',
  }
}
