name: Build storybook
on:
  workflow_dispatch:
    inputs:
      kuberta_system:

jobs:
  build:
    name: Build storybook
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: docker://quay.csssr.cloud/csssr/kuberta-init-workflow:v1

      - uses: docker://quay.csssr.cloud/csssr/github-info:v1
        id: gh

      - name: Download CSSSR actions
        uses: actions/checkout@v4
        with:
          repository: CSSSR/actions
          ssh-key: ${{ secrets.DOWNLOAD_ACTIONS_SSH_KEY }}
          path: actions

      - uses: actions/checkout@v4
        with:
          path: blog

      - uses: actions/setup-node@v4
        with:
          node-version: '14.x'

      - run: yarn install --frozen-lockfile
        working-directory: blog

      - run: yarn build-storybook
        working-directory: blog
        env:
          BLOG_HOST: https://${{ steps.gh.outputs.releaseID }}.csssr-blog-storybook.csssr.cloud/

      - name: Import secrets
        id: secrets
        uses: ./actions/get-aws-s3-upload-creds/v1beta1
        with:
          VAULT_JWT_KEY: ${{secrets.VAULT_JWT_KEY}}

      - uses: ./actions/upload-static/v1beta1
        with:
          project-id: csssr-blog-storybook
          files: ./blog/storybook-static
          auth: 'aws:${{steps.secrets.outputs.AWS_ACCESS_KEY_ID}}:${{steps.secrets.outputs.AWS_SECRET_ACCESS_KEY}}:${{steps.secrets.outputs.AWS_SESSION_TOKEN}}'
