name: Storybook
on:
  workflow_dispatch:
    inputs:
      kuberta_system:

jobs:
  build:
    name: Build Storybook
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: docker://quay.csssr.cloud/csssr/kuberta-init-workflow:v1

      - uses: docker://quay.csssr.cloud/csssr/github-info:v1
        id: gh

      - name: Download CSSSR actions
        uses: actions/checkout@v2
        with:
          repository: CSSSR/actions
          ssh-key: ${{ secrets.DOWNLOAD_ACTIONS_SSH_KEY }}
          path: actions

      - uses: actions/checkout@v2
        with:
          path: blog

      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - run: yarn install --frozen-lockfile
        working-directory: blog

      - run: yarn build-storybook
        working-directory: blog
        env:
          BLOG_HOST: https://${{ steps.gh.outputs.releaseID }}.csssr-blog-storybook.csssr.cloud/

      - name: Import secrets
        id: secrets
        uses: hashicorp/vault-action@v2.4.0
        with:
          url: https://vault.csssr.com:8200
          jwtGithubAudience: ${{secrets.VAULT_JWT_KEY}}
          role: s3-cdn-upload
          method: jwt
          exportEnv: false
          secrets: |
            aws/sts/s3-cdn-upload access_key | AWS_ACCESS_KEY_ID ;
            aws/sts/s3-cdn-upload secret_key | AWS_SECRET_ACCESS_KEY ;
            aws/sts/s3-cdn-upload security_token | AWS_SESSION_TOKEN ;

      - uses: ./actions/upload-static/v1beta1
        with:
          project-id: csssr-blog-storybook
          files: ./blog/storybook-static
          auth: 'aws:${{steps.secrets.outputs.AWS_ACCESS_KEY_ID}}:${{steps.secrets.outputs.AWS_SECRET_ACCESS_KEY}}:${{steps.secrets.outputs.AWS_SESSION_TOKEN}}'
