name: Деплой блога на тестинг
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  deploy:
    name: Сборка
    runs-on: ubuntu-latest

    steps:
      - name: Download CSSSR actions
        uses: actions/checkout@v2
        with:
          repository: CSSSR/actions
          token: ${{ secrets.DOWNLOAD_ACTIONS_TOKEN }}
          path: actions

      - uses: actions/checkout@v2
        with:
          path: new_blog

      - uses: actions/setup-node@v2-beta
        with:
          registry-url: 'https://npm.pkg.github.com'
          scope: '@csssr'

      - name: Install dependencies
        working-directory: new_blog
        run: yarn install --frozen-lockfile
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build testing
        working-directory: new_blog
        run: BLOG_HOST=http://$(node scripts/getReleaseID.js).csssr-new-blog.csssr.cloud yarn build

      - name: Деплой на тестинг
        uses: ./actions/deploy-static-site/v1beta1
        with:
          auth: ${{ secrets.CSSSR_AUTH }}
          token: ${{ secrets.GITHUB_TOKEN }}
          site-type: mpa
          project-id: csssr-new-blog
          files: ./new_blog/out
          no-previous-files: "true"
          not-found-page: 404/index.html
          values: |
            ingress:
              annotations:
                nginx.ingress.kubernetes.io/server-snippet: |
                  rewrite ^/$ /en redirect;
