name: Деплой блога
on:
  push:
    branches: [stable]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  deploy:
    name: Сборка
    runs-on: ubuntu-latest

    steps:
      - name: Download CSSSR actions
        uses: actions/checkout@v2
        with:
          repository: CSSSR/actions
          token: ${{ secrets.DOWNLOAD_ACTIONS_TOKEN }}
          path: actions

      - uses: actions/checkout@v2
        with:
          path: new_blog

      - uses: actions/setup-ruby@v1
        with:
          ruby-version: "2.7"

      - name: Install dependencies
        working-directory: new_blog
        run: |
          gem install bundler:1.17.1
          bundle install
      - run: bundle exec jekyll build
        working-directory: new_blog

      - name: Деплой на тестинг
        uses: ./actions/deploy-static-site/v1beta1
        with:
          auth: ${{ secrets.CSSSR_AUTH }}
          token: ${{ secrets.GITHUB_TOKEN }}
          site-type: mpa
          project-id: csssr-new-blog
          files: new_blog/out
          no-previous-files: "true"
          not-found-page: 404.html

      - name: Деплой на продакшен
        uses: ./actions/deploy-static-site/v1beta1
        if: github.ref == 'refs/heads/stable'
        with:
          auth: ${{ secrets.CSSSR_AUTH }}
          token: ${{ secrets.GITHUB_TOKEN }}
          site-type: mpa
          project-id: csssr-new-blog
          host: blog.csssr.ru
          www: "true"
          environment: production
          not-found-page: 404.html