name: Деплой блога на прод
on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Сборка прода
    runs-on: ubuntu-latest

    steps:
      - name: Download CSSSR actions
        uses: actions/checkout@v2
        with:
          repository: CSSSR/actions
          token: ${{ secrets.DOWNLOAD_ACTIONS_TOKEN }}
          path: actions

      - uses: actions/checkout@v2
        with:
          path: new_blog_prod

      - uses: actions/setup-node@v2-beta
        with:
          registry-url: 'https://npm.pkg.github.com'
          scope: '@csssr'

      - name: Install dependencies
        working-directory: new_blog_prod
        run: yarn install --frozen-lockfile
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build prod
        working-directory: new_blog_prod
        run: yarn build
        env:
          IS_PRODUCTION: 'TRUE'
          BLOG_HOST: https://blog.csssr.com

      - name: Деплой на продакшен
        uses: ./actions/deploy-static-site/v1beta1
        with:
          auth: ${{ secrets.CSSSR_AUTH }}
          token: ${{ secrets.GITHUB_TOKEN }}
          site-type: mpa
          project-id: csssr-new-blog
          files: ./new_blog_prod/out
          no-previous-files: "true"
          not-found-page: 404/index.html
          host: blog.csssr.com
          environment: production
          values: |
            ingress:
              annotations:
                nginx.ingress.kubernetes.io/server-snippet: |
                  rewrite ^/$ /en redirect;
