name: Деплой блога на test-blog.csssr.com
on:
  push:
    branches:
      - test-blog
concurrency: test_blog_environment

jobs:
  deploy:
    name: Сборка прода
    runs-on: ubuntu-latest

    steps:
      - name: Download CSSSR actions
        uses: actions/checkout@v2
        with:
          repository: CSSSR/actions
          ssh-key: ${{ secrets.DOWNLOAD_ACTIONS_SSH_KEY }}
          path: actions

      - uses: actions/checkout@v2
        with:
          path: new_blog_prod
          ref: ${{ github.event.pull_request.head.sha }}

      - uses: actions/setup-node@v2-beta
        with:
          registry-url: 'https://npm.pkg.github.com'
          scope: '@csssr'

      - name: Install dependencies
        working-directory: new_blog_prod
        run: yarn install --frozen-lockfile
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_GITHUB_REGISTRY_TOKEN }}

      - name: Build prod
        working-directory: new_blog_prod
        run: yarn build
        env:
          IS_PRODUCTION: 'TRUE'
          BLOG_HOST: https://test-blog.csssr.com
          COM_HOST: https://csssr.com

      - name: Деплой на продакшен
        uses: ./actions/deploy-static-site/v1beta1
        with:
          auth: ${{ secrets.CSSSR_AUTH }}
          token: ${{ secrets.GITHUB_TOKEN }}
          site-type: mpa
          project-id: csssr-test-blog
          files: ./new_blog_prod/out
          no-previous-files: 'true'
          not-found-page: 404/index.html
          host: test-blog.csssr.com
          environment: production
          values: |
            cache: cloudflare-worker
            invalidateCache: true
            reduceHttpRedirects: enabled
            ingress:
              annotations:
                nginx.ingress.kubernetes.io/server-snippet: |
                  more_set_headers 'X-Robots-Tag: noindex, nofollow';
                  rewrite ^/$ https://$http_host/en redirect;
