name: Lighthouse CI

on:
  deployment_status

jobs:
  run:
    name: Запуск Lighthouse по url стенда и валидация по установленным assertions
    runs-on: ubuntu-latest
    if: github.event.deployment_status.state == 'success'
    steps:
      - uses: actions/checkout@v2
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: Export LHCI_BUILD_CONTEXT__CURRENT_BRANCH
        shell: bash
        run: export LHCI_BUILD_CONTEXT__CURRENT_BRANCH=${{ steps.extract_branch.outputs.branch }}
      - run: |
          npx @lhci/cli@0.4.x autorun --collect.url=${{ github.event.deployment.payload.environmentURL }}/en --collect.url=${{ github.event.deployment.payload.environmentURL }}/en/article/offshore-web-development
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}