name: Запуск проверки Lighthouse CI

on:
  deployment_status

jobs:
  run:
    name: Проверка Lighthouse CI
    runs-on: ubuntu-latest
    if: github.event.deployment_status.state == 'success'
    steps:
    - run: |
        npx @lhci/cli@0.4.x autorun --collect.url=${{ github.event.deployment.payload.environmentURL }}/en --collect.url=${{ github.event.deployment.payload.environmentURL }}/en/article/offshore-web-development
      env:
        LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}